---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vizier-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vizier-core
subjects:
- kind: ServiceAccount
  name: vizier-core
  namespace: katib
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: vizier-core
rules:
  - verbs: ["*"]
    apiGroups: ["extensions"] 
    resources: ["ingresses","ingresses/status","deployments","deployments/status"] 
  - verbs: ["*"]
    apiGroups: [""] 
    resources: ["services"] 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vizier-core
  namespace: katib
