apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tensorboard
  namespace: katib
  labels:
    app: tensorboard
spec:
  replicas: 1
  template:
    metadata:
      name: tensorboard
      labels:
        app: tensorboard
    spec:
      containers:
      - name: tensorboard
        image: gcr.io/tensorflow/tensorflow:latest
        imagePullPolicy: Always
        args:
          - '/usr/local/bin/tensorboard'
          - '--port=80'
        ports:
        - name: webui
          containerPort: 80
        resources:
          requests:
            cpu: 500m
            memory: 500M
          limits:
            cpu: 500m
            memory: 500M
