 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: tensorboard
   namespace: katib
 spec:
   rules:
   - host: k-cluster.example.net
     http:
       paths:
       - path: /tensorboard
         backend:
          serviceName: tensorboard-tid
          servicePort: 80
