apiVersion: v1
kind: Service
metadata:
  name: tensorboard-tid
  namespace: katib
  labels:
    app: tensorboard
    component: tid
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: api
  selector:
    app: tensorboard
