apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: modeldb-backend
  namespace: katib
  labels:
    app: modeldb
    component: backend
spec:
  replicas: 1
  template:
    metadata:
      name: modeldb-backend
      labels:
        app: modeldb
        component: backend
    spec:
      containers:
      - name: modeldb-backend
        image: mitdbg/modeldb-backend:latest
        args:
          - 'modeldb-db'
        ports:
        - name: api
          containerPort: 6543
#        resources:
#          requests:
#            cpu: 500m
#            memory: 500M
#          limits:
#            cpu: 500m
#            memory: 500M
