apiVersion: v1
kind: Service
metadata:
  name: modeldb-backend
  namespace: katib
  labels:
    app: modeldb
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: 6543
      protocol: TCP
      name: api
  selector:
    app: modeldb
    component: backend
