apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: modeldb-db
  namespace: katib
  labels:
    app: modeldb
    component: db
spec:
  replicas: 1
  template:
    metadata:
      name: modeldb-db
      labels:
        app: modeldb
        component: db
    spec:
      containers:
      - name: modeldb-db
        image: mongo:3.4
        ports:
        - name: dbapi
          containerPort: 27017
#        resources:
#          requests:
#            cpu: 500m
#            memory: 500M
#          limits:
#            cpu: 500m
#            memory: 500M
