apiVersion: v1
kind: Service
metadata:
  name: modeldb-db
  namespace: katib
  labels:
    app: modeldb
    component: db
spec:
  type: ClusterIP
  ports:
    - port: 27017
      protocol: TCP
      name: dbapi
  selector:
    app: modeldb
    component: db
