apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizier-db
  namespace: katib
  labels:
    app: vizier
    component: db
spec:
  replicas: 1
  template:
    metadata:
      name: vizier-db
      labels:
        app: vizier
        component: db
    spec:
      containers:
      - name: vizier-db
        image: mysql:8.0.3
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "test"
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "true"
          - name: MYSQL_DATABASE
            value: "vizier"
        ports:
        - name: dbapi
          containerPort: 3306
#        resources:
#          requests:
#            cpu: 500m
#            memory: 500M
#          limits:
#            cpu: 500m
#            memory: 500M
