apiVersion: v1
kind: Service
metadata:
  name: vizier-db
  namespace: katib
  labels:
    app: vizier
    component: db
spec:
  type: ClusterIP
  ports:
    - port: 3306
      protocol: TCP
      name: dbapi
  selector:
    app: vizier
    component: db
