apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dlk-manager
  namespace: katib
  labels:
    app: dlk
    component: manager
spec:
  replicas: 1
  template:
    metadata:
      name: dlk-manager
      labels:
        app: dlk
        component: manager
    spec:
      serviceAccountName: dlk-manager
      containers:
      - name: dlk-manager
        image: katib/dlk-manager
        imagePullPolicy: Always
        args:
          - 'dlkmanager'
          - '--scheduler'
          - 'dlk'
        ports:
        - name: webapi
          containerPort: 1323
#        resources:
#          requests:
#            cpu: 500m
#            memory: 500M
#          limits:
#            cpu: 500m
#            memory: 500M
