---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dlk-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dlk-manager
subjects:
- kind: ServiceAccount
  name: dlk-manager
  namespace: katib
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dlk-manager
rules:
  - apiGroups: [""] 
    resources: ["pods", "nodes", "nodes/*", "pods/log", "pods/status", "services", "persistentvolumes", "persistentvolumes/status","persistentvolumeclaims","persistentvolumeclaims/status"] 
    verbs: ["*"]
  - apiGroups: ["batch"] 
    resources: ["jobs", "jobs/status"] 
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dlk-manager
  namespace: katib
