apiVersion: v1
kind: Service
metadata:
  name: dlk-manager
  namespace: katib
  labels:
    app: dlk
    component: manager
spec:
  type: ClusterIP
  ports:
    - port: 1323
      protocol: TCP
      name: api
  selector:
    app: dlk
    component: manager
