apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: modeldb-frontend
  namespace: katib
  labels:
    app: modeldb
    component: frontend
spec:
  replicas: 1
  template:
    metadata:
      name: modeldb-frontend
      labels:
        app: modeldb
        component: frontend
    spec:
      containers:
      - name: modeldb-frontend
        image: katib/katib-frontend
        imagePullPolicy: Always
        args:
          - 'modeldb-backend'
        env:
          - name: ROOT_PATH
            value: "/katib"
        ports:
        - name: webapi
          containerPort: 3000
#        resources:
#          requests:
#            cpu: 500m
#            memory: 500M
#          limits:
#            cpu: 500m
#            memory: 500M
