 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: katib-ui
   namespace: katib
 spec:
   rules:
   - host: k-cluster.example.net
     http:
       paths:
       - path: /katib
         backend:
          serviceName: modeldb-frontend
          servicePort: 3000
